name: TEST CI/CD

on:
  push:
    branches: [ main ]

jobs:
  api-ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Grant execute permission for gradlew
        run: |
          if [ ${{ github.ref_name }} = "main" ]
          then echo "Hello Main"
          fi 

          if [ ${{ github.ref_name }} = "develop" ]
          then echo "Hello Develop"
          fi 
        
