name: TEST CI/CD

on:
  push:
    branches: [ main ]

jobs:
  api-ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Grant execute permission for gradlew
        run: |
          branchName=""

          if [ ${{ github.ref_name }} = "main" ]
          then 
          branchName="Main"
          echo "Hello Main"
          fi 

          if [ ${{ github.ref_name }} = "develop" ]
          branchName="Develop"
          then echo "Hello Develop"
          fi 
          echo "${branchName}"
          echo ${branchName}
        
